# Generated by Django 2.1.7 on 2019-02-25 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20190225_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('age', models.IntegerField()),
                ('worksFor', models.CharField(max_length=32, verbose_name='所属公司')),
                ('img', models.ImageField(upload_to='', verbose_name='个人照')),
                ('summy', models.CharField(max_length=200, verbose_name='简介')),
                ('salary', models.FloatField(verbose_name='薪资/月')),
            ],
            options={
                'verbose_name_plural': '学生信息',
            },
        ),
        migrations.CreateModel(
            name='StudentMore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moreInfo', models.CharField(max_length=1000, verbose_name='更多想说的')),
            ],
            options={
                'verbose_name_plural': '学生更多信息',
            },
        ),
        migrations.AlterModelOptions(
            name='classes',
            options={'verbose_name_plural': '课程'},
        ),
        migrations.AlterModelOptions(
            name='companny',
            options={'verbose_name_plural': '企业合作'},
        ),
        migrations.AlterModelOptions(
            name='headphoto',
            options={'verbose_name_plural': '轮播图'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': '最新公告'},
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='more',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app01.StudentMore'),
        ),
    ]
