# Generated by Django 2.1.7 on 2019-02-25 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20190225_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='age',
            field=models.IntegerField(verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='more',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app01.StudentMore', verbose_name='更多信息'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='name',
            field=models.CharField(max_length=32, verbose_name='姓名'),
        ),
    ]
