# Generated by Django 2.1.7 on 2019-02-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20190225_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headphoto',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='图骗'),
        ),
        migrations.AlterField(
            model_name='headphoto',
            name='name',
            field=models.CharField(max_length=32, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='headphoto',
            name='target',
            field=models.CharField(max_length=48, verbose_name='链接地址'),
        ),
        migrations.AlterField(
            model_name='headphoto',
            name='weight',
            field=models.BooleanField(verbose_name='权重'),
        ),
    ]
