# Generated by Django 2.1.7 on 2019-02-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20190225_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headphoto',
            name='img',
            field=models.CharField(max_length=48, verbose_name='图骗地址'),
        ),
    ]
