# Generated by Django 2.1.7 on 2019-02-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_auto_20190225_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companny',
            name='ComPhoto',
            field=models.ImageField(default='/static/images/c1.jpg', upload_to='static/images', verbose_name='公司LOGO'),
        ),
    ]
