# Generated by Django 2.1.7 on 2019-02-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_auto_20190225_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companny',
            name='ComPhoto',
            field=models.ImageField(upload_to='static/images', verbose_name='公司LOGO'),
        ),
    ]
