# Generated by Django 2.1.7 on 2019-02-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_auto_20190225_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companny',
            name='ComPhoto',
            field=models.CharField(max_length=48, verbose_name='公司LOGO'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='img',
            field=models.CharField(max_length=48, verbose_name='个人照'),
        ),
    ]
