# Generated by Django 2.1.7 on 2019-02-27 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_auto_20190225_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='方向')),
            ],
        ),
        migrations.CreateModel(
            name='grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='等级')),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='学科')),
            ],
        ),
        migrations.CreateModel(
            name='videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('href', models.CharField(max_length=32, verbose_name='链接地址')),
                ('img', models.CharField(max_length=32, verbose_name='图片链接')),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='include',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vTOs', to='app01.videos', verbose_name='包含视频'),
        ),
        migrations.AddField(
            model_name='grade',
            name='include',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vTOg', to='app01.videos', verbose_name='包含视频'),
        ),
        migrations.AddField(
            model_name='direction',
            name='include',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vTOd', to='app01.videos', verbose_name='包含视频'),
        ),
    ]
