# Generated by Django 2.1.7 on 2019-02-28 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_auto_20190227_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direction',
            name='include',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='include',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='include',
        ),
        migrations.DeleteModel(
            name='direction',
        ),
        migrations.DeleteModel(
            name='grade',
        ),
        migrations.DeleteModel(
            name='subject',
        ),
        migrations.DeleteModel(
            name='videos',
        ),
    ]
