# Generated by Django 2.1.7 on 2019-02-28 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0014_auto_20190228_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='方向')),
            ],
            options={
                'verbose_name_plural': '筛选方向',
            },
        ),
        migrations.CreateModel(
            name='grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='等级')),
            ],
            options={
                'verbose_name_plural': '筛选等级',
            },
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='学科')),
            ],
            options={
                'verbose_name_plural': '筛选学科',
            },
        ),
        migrations.CreateModel(
            name='videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('href', models.CharField(max_length=32, verbose_name='链接地址')),
                ('img', models.CharField(max_length=32, verbose_name='图片链接')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.grade')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.subject')),
            ],
            options={
                'verbose_name_plural': '筛选视频',
            },
        ),
        migrations.AddField(
            model_name='direction',
            name='suject',
            field=models.ManyToManyField(to='app01.subject'),
        ),
    ]
