# Generated by Django 2.1.7 on 2019-02-28 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0015_auto_20190228_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='direction',
            old_name='suject',
            new_name='subject',
        ),
    ]
