# Generated by Django 2.1.7 on 2019-02-28 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0016_auto_20190228_1710'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Classes',
        ),
        migrations.DeleteModel(
            name='Companny',
        ),
        migrations.RemoveField(
            model_name='direction',
            name='subject',
        ),
        migrations.DeleteModel(
            name='HeadPhoto',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='more',
        ),
        migrations.RemoveField(
            model_name='videos',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='videos',
            name='subject',
        ),
        migrations.DeleteModel(
            name='direction',
        ),
        migrations.DeleteModel(
            name='grade',
        ),
        migrations.DeleteModel(
            name='StudentInfo',
        ),
        migrations.DeleteModel(
            name='StudentMore',
        ),
        migrations.DeleteModel(
            name='subject',
        ),
        migrations.DeleteModel(
            name='videos',
        ),
    ]
