# Generated by Django 2.1.7 on 2019-02-28 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app01', '0017_auto_20190228_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='课程名称')),
                ('summy', models.CharField(max_length=200, verbose_name='课程简介')),
                ('img', models.CharField(max_length=48, verbose_name='课程LOGO')),
            ],
            options={
                'verbose_name_plural': '课程',
            },
        ),
        migrations.CreateModel(
            name='Companny',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='公司名称')),
                ('ComPhoto', models.CharField(max_length=48, verbose_name='公司LOGO')),
                ('ComAddr', models.CharField(max_length=48, verbose_name='链接地址')),
            ],
            options={
                'verbose_name_plural': '企业合作',
            },
        ),
        migrations.CreateModel(
            name='direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='方向')),
            ],
            options={
                'verbose_name_plural': '筛选方向',
            },
        ),
        migrations.CreateModel(
            name='grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='等级')),
            ],
            options={
                'verbose_name_plural': '筛选等级',
            },
        ),
        migrations.CreateModel(
            name='HeadPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.BooleanField(verbose_name='权重')),
                ('name', models.CharField(max_length=32, verbose_name='标题')),
                ('target', models.CharField(max_length=48, verbose_name='链接地址')),
                ('img', models.CharField(max_length=48, verbose_name='图骗地址')),
            ],
            options={
                'verbose_name_plural': '轮播图',
            },
        ),
        migrations.CreateModel(
            name='imgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='static/images', verbose_name='图片')),
                ('src', models.CharField(max_length=48, verbose_name='图片链接')),
                ('title', models.CharField(max_length=16, verbose_name='标题')),
                ('sumary', models.CharField(max_length=128, verbose_name='简介')),
            ],
            options={
                'verbose_name_plural': '筛选视频',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('summy', models.CharField(max_length=200, verbose_name='简介')),
                ('detail', models.CharField(max_length=1000, verbose_name='更多信息')),
            ],
            options={
                'verbose_name_plural': '最新公告',
            },
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('worksFor', models.CharField(max_length=32, verbose_name='所属公司')),
                ('img', models.CharField(max_length=48, verbose_name='个人照')),
                ('summy', models.CharField(max_length=200, verbose_name='简介')),
                ('salary', models.FloatField(verbose_name='薪资/月')),
            ],
            options={
                'verbose_name_plural': '学生信息',
            },
        ),
        migrations.CreateModel(
            name='StudentMore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moreInfo', models.CharField(max_length=1000, verbose_name='更多想说的')),
            ],
            options={
                'verbose_name_plural': '学生更多信息',
            },
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='学科')),
            ],
            options={
                'verbose_name_plural': '筛选学科',
            },
        ),
        migrations.CreateModel(
            name='videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('href', models.CharField(max_length=32, verbose_name='链接地址')),
                ('img', models.CharField(max_length=32, verbose_name='图片链接')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.grade')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.subject')),
            ],
            options={
                'verbose_name_plural': '筛选视频',
            },
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='more',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app01.StudentMore', verbose_name='更多信息'),
        ),
        migrations.AddField(
            model_name='direction',
            name='subject',
            field=models.ManyToManyField(to='app01.subject'),
        ),
    ]
