# Generated by Django 2.1.7 on 2019-02-28 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0018_auto_20190228_2051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imgs',
            options={'verbose_name_plural': '图片集'},
        ),
    ]
